package com.testCase.userAdmin;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;


//Used to map the class to the table account
@Entity
public class Account implements Serializable{

	private static final long serialVersionUID = 1L;

	//Map the primary key, generated by the DB
	@Id
	@GeneratedValue(generator = "account_account_id_seq", strategy = GenerationType.SEQUENCE)
	  @SequenceGenerator(
	      name = "account_account_id_seq", 
	      sequenceName = "account_account_id_seq", 
	      allocationSize = 50
	  )
	private long account_id;
	
    private String iban;
    private String account_number;
    
	//Map a value that is generated by the DB
    @Generated(GenerationTime.ALWAYS)
    private String owner;
    
	//Map the relation many to one, from the account to his user, represented by a single BankUser
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name = "USER_ID")
    private BankUser fk_user_id;

	public long getAccount_id() {
		return account_id;
	}

	public String getIban() {
		return iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public String getAccount_number() {
		return account_number;
	}

	public void setAccount_number(String account_number) {
		this.account_number = account_number;
	}

	public String getOwner() {
		return owner;
	}

	public BankUser getFk_user_id() {
		return fk_user_id;
	}

	public void setFk_user_id(BankUser fk_user_id) {
		this.fk_user_id = fk_user_id;
	}
	
    
}
