package com.testCase.userAdmin;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

//Used to map the class to the table bankuser
@Entity
public class BankUser implements Serializable{

	private static final long serialVersionUID = 1L;

	//Map the primary key, generated by the DB
	@Id
    @GeneratedValue
    private long user_id;
	
	private String first_name;
	private String last_name;
	
	//Map a value that is generated by the DB
	@Generated(GenerationTime.ALWAYS)
    private String owner;
	
	//Map the relation one to many, from the user to the accounts, represented by a list of accounts
	@OneToMany(mappedBy = "fk_user_id")
	private List<Account> accounts = new ArrayList<Account>();

	public long getUser_id() {
		return user_id;
	}

	public String getFirst_name() {
		return first_name;
	}

	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}

	public String getLast_name() {
		return last_name;
	}

	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}

	public String getOwner() {
		return owner;
	}

	public List<Account> getAccounts() {
		return accounts;
	}

	public void setAccounts(List<Account> accounts) {
		this.accounts = accounts;
	}
	
	
}
