package com.testCase.userAdmin.Entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

//Used to map the class to the table bankuser
@Entity
public class BankUser implements Serializable{

	private static final long serialVersionUID = 1L;

	//Map the primary key, generated by the DB
	@Id
	@GeneratedValue(generator = "bankuser_user_id_seq", strategy = GenerationType.SEQUENCE)
	  @SequenceGenerator(
	      name = "bankuser_user_id_seq", 
	      sequenceName = "bankuser_user_id_seq", 
	      allocationSize = 50
	  )
    private long user_id;
	
	@Column(nullable = false)
	private String first_name;
	@Column(nullable = false)
	private String last_name;
	
	//Map a value that is automatically generated by the DB
	@Column(nullable = false)
	@Generated(GenerationTime.ALWAYS)
    private String owner;
	
	//Map the relation one to many, from the user to the accounts, represented by a list of accounts
	@OneToMany(mappedBy = "user")
	private List<Account> accounts = new ArrayList<Account>();

	public long getUser_id() {
		return user_id;
	}

	public String getFirst_name() {
		return first_name;
	}

	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}

	public String getLast_name() {
		return last_name;
	}

	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}

	public String getOwner() {
		return owner;
	}

	public List<Account> getAccounts() {
		return accounts;
	}

	public void setAccounts(List<Account> accounts) {
		this.accounts = accounts;
	}
	
	
}
